### ISSUE TITLE
配置文件分配的内存太多了:<

### ISSUE THREAD

**Issue by xcwen** [TarsPHP/tars-utils#1]
class Conf
{
    private static $_swooleTable;
    const SWOOLE_TABLE_SET_FAILED = -1001;
    const SWOOLE_TABLE_GET_FAILED = -1002;
    const KEY = 'tars:php:tarsConf';
    private function __construct()
    {
        self::$_swooleTable = new \swoole_table(20000);
        self::$_swooleTable->column('tarsConfig', \swoole_table::TYPE_STRING, 10000);
        self::$_swooleTable->create();
    }
200M 啊:<

在内存小的机器经常:
 PHP Fatal error:  Swoole\Table::create(): unable to allocate memory. in /usr/local/app/tars/tarsnode/data
/Leo.httpYbCore/bin/src/vendor/phptars/tars-utils/src/Conf.php on line 24

**Comment by meijing0114** [comment]
already fixed, please run composer update to fetch newest tars-utils version: v0.1.2

**Comment by xcwen** [comment]
thanks :>
